# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Required for CSRF token storage
    session: true

    #esi: true
    #fragments: true

    # HTTP Client configuration
    http_client:
        default_options:
            timeout: 10
            max_redirects: 3

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
